Plugin implementation
nebula-plugins/nebula-hollow-plugin pull request #1
Opened 2017-03-21 06:55 UTC by IgorPerikov

2017-03-21 19:37 UTC, ghost requested changes
Looks like good stuff to me, @IgorPerikov. I only found a few changes I'd like to see. I'm also going to ask one of our gradle plugin experts to give this PR a review.

One general recommendation they made was to author the plugin in Java instead of Groovy. In their experience we've had performance problems with plugins written in Groovy. If you're interested in porting this to pure Java go ahead. This is a suggestion, not a requirement.

2017-03-21 19:37 UTC, toolbear commented on README.md
> +        mavenLocal()
I don't believe `mavenLocal()` is necessary. We need it to work on the plugin ourselves, but once the plugin is released I think only `jcenter()` is required.

2017-03-21 19:37 UTC, toolbear commented on README.md
> +apply plugin: 'nebula.hollow-plugin'
We want this to be `apply plugin: 'nebula.hollow'`. I wonder what we need to change to make it work that way?

2017-03-21 19:37 UTC, toolbear commented on build.gradle
> +    vcsUrl = 'https://github.com/nebula-plugins/hollow-plugin'
Small typo: `/hollow-plugin` should be `/nebula-hollow-plugin`

2017-03-21 19:37 UTC, toolbear commented on build.gradle
> +            id = 'nebula.hollow-plugin'
Maybe `id = 'nebula.hollow'` is what we need to change it to?

2017-03-21 19:37 UTC, toolbear commented on README.md
> +        mavenLocal()
I see your `TODO` further down regarding this. I believe there a TODO is fine. For this README we can write instructions assuming hollow plugin has been published.

2017-03-21 19:59 UTC, IgorPerikov commented on build.gradle
> +            id = 'nebula.hollow-plugin'
yes, that's the 1st part of total work, 2nd is to rename `nebula.hollow-plugin.properties` to `nebula.hollow.properties`

2017-03-21 20:01 UTC, IgorPerikov commented on README.md
> +apply plugin: 'nebula.hollow-plugin'
discussed here https://github.com/nebula-plugins/nebula-hollow-plugin/pull/1#discussion_r107259629

2017-03-21 20:04 UTC, IgorPerikov commented on README.md
> +        mavenLocal()
ye, I agree with that

2017-03-21 20:09 UTC, IgorPerikov commented
> One general recommendation they made was to author the plugin in Java instead of Groovy. In their experience we've had performance problems with plugins written in Groovy. If you're interested in porting this to pure Java go ahead. This is a suggestion, not a requirement.

Sure, I'll convert it to java7 implementation. Honestly, my first implementation was made with java, then I looked through most popular nebula-plugins and realised, that groovy might be more idiomatic for plugins :smile:

2017-03-21 21:18 UTC, IgorPerikov commented
@toolbear 
https://github.com/nebula-plugins/nebula-hollow-plugin/pull/1/commits/898dd50756ecb11e436afbfaf845eaf6caf6a13e :

1. ports plugin source code from groovy to java
2. makes `apply plugin: 'nebula.hollow'` usage instead of `apply plugin: 'nebula.hollow-plugin'`
3. adds testcase, that checks that recursive scan works well
4. fixes `vcsUrl` typo and removes `mavenLocal()` section from readme

2017-03-24 20:34 UTC, ghost approved these changes

2017-03-24 20:35 UTC, toolbear commented
@IgorPerikov considering this is a brand new plugin that hasn't been announced, this is good to merge and we can iterate from there on other refinements.

Thanks for making this, BTW!

2017-03-24 20:35 UTC, merged